[package]
name = "kiku"
authors = ["xuwenxiang256@outloook.com"]
version = "0.1.0"
edition = "2021"

[[bin]]
name = "kiku"
path = "./src/bin/main.rs"

[target.'cfg(unix)'.dependencies]
chardet = "0.2.4"
crossterm = "0.29.0"
unicode-width = "0.2.1"
